- name: disbale nodejs service
  ansible.builtin.command: dnf module disable nodejs -y

- name: enable nodejs20 service
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs and mysql service
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: 
    - mysql
    - nodejs 

- name: create user expense
  ansible.builtin.user:
    name: expense

- name: create a directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: download the appalication file
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip

- name: unzip the file to app folder
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

- name: download the dependency
  ansible.builtin.command: npm install
  args:
    chdir: /app

- name: copy the backend service file
  ansible.builtin.teplate:
    src: backend.service.j2
    dest: /etc/systemd/system/backend.service

- name: install the pip dependencies
  ansible.builtin.pip:
    name: 
      - PyMySQL
      - cryptography
    executable: pip3.9

- name: import of sql data
  community.mysql.mysql_db:
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: "{{ login_host }}"
    state: import
    name: all
    target: /app/schema/backend.sql

- name: daemon reload
  ansible.builtin.systemd_service:
    state: restarted
    name: backend
