- name: install the nginx server
  ansible.builtin.package:
    name: nginx
    state: present

- name: enable the nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes

- name: remove the existing html files directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: download the appalication file
  ansible.builtin.get_url:
    url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
    dest: /tmp/frontend.zip

- name: unzip the file to app folder
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copy the expense file
  ansible.builtin.template:
    src: expense.conf.j2
    dest: /etc/nginx/default.d/expense.conf
  notify:
  - Restart nginx

# - name: enable the nginx service
#   ansible.builtin.service:
#     name: nginx
#     state: restarted 